### PR TITLE
Breakfast Notes and Dinner Recipe Name update

### LINKED ISSUE #16: Breakfast - Notes
## 💬 Discussion topic

Breakfast

## 👥 People to consult

@fbosselin @Tojtt 

## 📃 Details

Adding Breakfast Notes for the chia seed pudding recipe

### LINKED ISSUE #18: Dinner Recipe Name
## ❗ Potential issues

Potential Bad Name

## 👥 People to consult

@penglb @chaley17 

## 📃 Details

Updating Dinner Recipe Name

### PR DESCRIPTION
**Pull request by unsanforized**
## 🎯 Objective

Adding Notes for Breakfast Recipe

## 🛠️ Changes made

Added Notes for Breakfast Recipe

## 👥 Who needs to review this Pull Request? 

@fbosselin  @Tojtt 

_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Review by hoangcto — APPROVED** [review]
This LGTM! :)

**Comment by fbosselin** [comment]
Looks good!

**Review by fbosselin — APPROVED** [review]

**Comment by fbosselin** [comment]
To understand the best practice. Who has to merge the approved PR? The creator or the last one to review/approve?

**Comment by hoangcto** [comment]
Its the approvers since they usually own the repo. If you are an outside contributor, you won’t be able to merge it

**Pull request merged**
