### PR TITLE
Close #1 name to breakfast recipe and #4 equipment list for breakfast

### LINKED ISSUE #1: Breakfast - Recipe Name
## 💬 Discussion topic

We need to add name for the breakfast recipe

## ❗ Potential issues

We won't know how to build the recipe without knowing what it is.

## 👥 People to consult

@penglb @unsanforized 

## 📃 Details

Add name to doc

### LINKED ISSUE #4: Breakfast - Equipment
## 💬 Discussion topic

Need to figure out what equipment are needed

## ❗ Potential issues

Cannot make food without the right tools

## 👥 People to consult

@luisfego @chaley17 

## 📃 Details

@Tojtt to figure out what equipment is needed and add to breakfast recipe 😃

### PR DESCRIPTION
**Pull request by hoangcto**
Closing out Issue #1 and Issues #4 

## 🎯 Objective

Adding name to breakfast recipe per Issue #1 
Adding equipment list to breakfast recipe per Issues #4 

## 🛠️ Changes made

Added breakfast name 
Added equipment list

## 👥 Who needs to review this Pull Request? 

@penglb @unsanforized

### CODE REVIEW

**Comment by penglb** [comment]
Could you adjust the recipe name so it says "Chia Seed" instead of just "Chia"? And can you put the equipment items on different lines or in a bulleted list? Otherwise, LGTM! 🍫

**Comment by hoangcto** [comment]
Yeah I made the updates @penglb. Can you approve and merge the PR?

**Comment by penglb** [comment]
Looks good to me, but think we need two reviewers per PR, so will wait for @unsanforized to also take a look 👀

**Review by penglb — APPROVED** [review]
Approved by me, thanks for the adjustments. @unsanforized can you also approve?

**Comment by unsanforized** [comment]
Lgtm

**Review by unsanforized — APPROVED** [review]

**Pull request merged**
