### PR TITLE
added breakfast servings

### LINKED ISSUE #5: Breakfast - servings
💬 Discussion topic
Need to figure out how many servings breakfast recipe will have

❗ Potential issues
May not make enough food without knowing how many servings per recipe

👥 People to consult
@Tojtt @penglb 

📃 Details
@chaley17 to figure out servings of breakfast recipe 😃

### PR DESCRIPTION
**Pull request by connor-haley**
## 🎯 Objective

added breakfast number of servings

## 🛠️ Changes made

3 servings, added that super useful info

## 👥 Who needs to review this Pull Request? 

@Tojtt please confirm this meets the criteria of your issue and approve if so! also @fbosselin please give it your eyes :)

### CODE REVIEW

**Review by hoangcto — CHANGES_REQUESTED** [review]
Can you bring the "3 tasty servings!" down a line + indent it so our format will be consistent

**Comment by connor-haley** [comment]
@Tojtt updated!

**Review by hoangcto — APPROVED** [review]
LGTM! Waiting for Lily approval

**Review by penglb — APPROVED** [review]
Looks like we'll have to double it if we want to feed our group 😝

**Pull request merged**
